### ISSUE TITLE
Adding support for [[wikilinks]]

### ISSUE THREAD

**Issue by jlcolbert** [Thomasorus/Chisai#6]
In the Mistune documentation, it gives an example of how to create a plugin for wiki style links, with brackets. I'm not code-literate enough to figure out how to implement it, though I have tried. Would it be possible to add that function to the mistune.py code?

**Comment by Thomasorus** [comment]
Hey, can you link me the documentation you’re talking about? If it’s not too complicated then he’s I might be able to add it.

**Comment by jlcolbert** [comment]
Sure, no problem!

https://mistune.readthedocs.io/en/latest/advanced.html#create-plugins

**Comment by Thomasorus** [comment]
You can try using them now. Please read the wiki and report any bug: https://github.com/Thomasorus/Chisai/wiki/Using-%5B%5Bwikilinks%5D%5D
